### ISSUE TITLE
Master switch no effect after 1.0.4 update

### ISSUE THREAD

**Issue by breadbakerman** [meg768/homebridge-pushover#6]
After the 1.0.4 update the master switch has no effect anymore. Notifications are pushed anyway regardless of the setting.
Besides that, great changes in 1.0.4.

Thank you.

**Comment by meg768** [comment]
Sorry for the change in behavior. There is no master switch anymore. It is automatically added by the platform name.

**Comment by meg768** [comment]
Every notification has a **name** and a **message** now. The **name**  is displayed under the button in HomeKit and the **message** is sent by Pushover. Will probably add **title** soon... 

```json
        {
            "platform": "Pushover",
            "name": "Messages",

            "pushover": {
                "user": "your-pushover-user",
                "token": "your-pushover-token"
            },

            "messages": [
                {
                    "name": "Larm på",
                    "message": "Larm aktiverat"
                },
                {
                    "name": "Larm av",
                    "message": "Larm avaktiverat"
                },
                {
                    "name": "Ringklocka",
                    "message": "Det ringer på dörren",
                    "priority": "high"
                }
            ]

        }
```

**Comment by meg768** [comment]
If this still doesn't work for you, please let me know...

**Comment by meg768** [comment]
To clarify..

```javascript
        {
            ...           
            "platform": "Pushover",
            "name": "Name of the Master Switch",
            ...
        }
```

**Comment by meg768** [comment]
Please report any problems you are having...

**Comment by breadbakerman** [comment]
Sorry for not being clear, I mean exactly that switch with the platform name (e.g. "Name of the Master Switch") that has no effect. 
Not really a big problem, though and I really like your changes splitting the name and the message into separate fields.

**Comment by meg768** [comment]
If you set the **"priority"** property to **"high"** the message is always sent regardless of the master switch state. However if you omit **"priority"** the message is only sent if the master switch is turned on.

This doesn't work for you?!

**Comment by breadbakerman** [comment]
Yes, works perfectly. 
Priority was indeed set to high on the first message I configured and the rest was copy pasta.

Thanks for your patience.
