### ISSUE TITLE
Instances that use a custom storage path can not use this plugin.

### ISSUE THREAD

**Issue by mkellsy** [meg768/homebridge-pushover#7]
Homebridge has a flag that allows you to change your config path. It isn't guaranteed to be in `~/.homebridge`.

There is a method available in the `homebridge.user` object variable called `storagePath`. This should be used.

Here is an example from your `index.js` file.

```
require('dotenv').config({path: Path.join(homebridge.user.storagePath(), '.env')});
```

**Comment by meg768** [comment]
Thanks! Updated the code. New release (1.0.10) on both npm and GitHub.
